<script setup>
import { ref, computed, onMounted, onUnmounted, watch } from 'vue';
import { BrowserProvider, Contract, formatEther, parseEther, isAddress } from 'ethers';
import { CONTRACT_ADDRESS, CHAIN_ID, RPC_URL, EXPLORER_URL, CONTRACT_ABI } from './config';
const brandLogoUrl = `${import.meta.env.BASE_URL}proofora-logo.png`;
const account = ref(''), chainId = ref(''), walletError = ref(''), connecting = ref(false), busy = ref(false), notice = ref('');
const activeView = ref('All missions'), search = ref(''), activeCategory = ref('All topics'), selected = ref(null), createOpen = ref(false), guideOpen = ref(false), mobileNav = ref(false);
const txHash = ref(''), missionForm = ref({title:'', category:'Market structure', description:'', deadline:'', reward:'', uri:''});
const evidence = ref(''), contribution = ref(''), submissionText = ref(''), contributions = ref([]), claimableAmount = ref('0'), walletBalance = ref('0'), networkTotals = ref({escrowed:'0',awarded:'0',claimed:'0'}), previewSaved = ref(JSON.parse(localStorage.getItem('proofora-saved') || '[]'));
const configured = computed(() => isAddress(CONTRACT_ADDRESS) && CONTRACT_ABI.length > 0);
const shortAccount = computed(() => account.value ? `${account.value.slice(0,6)}...${account.value.slice(-4)}` : 'Connect wallet');
const correctChain = computed(() => !!CHAIN_ID && BigInt(chainId.value || 0) === BigInt(CHAIN_ID));
const topics = ['All topics','Market structure','Tokenized assets','Ecosystem','Risk research'];
const missionItems = ref([
 {id:1,title:'What does a tokenized stock actually represent?',description:'Map the rights, custody models and settlement paths behind tokenized equities. Build a clear, source-linked comparison that anyone can use.',category:'Tokenized assets',tag:'FOUNDATION',reward:'0.08',submissions:0,color:'peach',icon:'o',difficulty:'Open brief',deadline:'Preview',sponsor:'Example sponsor',status:'Open',brief:'Compare at least three tokenized equity models. Identify legal rights, redemption paths, underlying custody, trading hours and geographic restrictions. Link every material claim to an original source. Highlight what cannot yet be independently verified.',deliverables:['One structured comparison with primary-source links','A rights and custody diagram','A short limitations and open questions section']},
 {id:2,title:'A field guide to the Robinhood Chain ecosystem',description:'Connect the dots between infrastructure, applications and the builders shaping a new financial network.',category:'Ecosystem',tag:'ECOSYSTEM MAP',reward:'0.05',submissions:0,color:'lavender',icon:'o',difficulty:'Open brief',deadline:'Preview',sponsor:'Example sponsor',status:'Open',brief:'Create an ecosystem map of confirmed, publicly announced projects. Separate live deployments from announced plans. Include original source URLs and record your last verification date.',deliverables:['A verifiable ecosystem directory','Deployment status and contract links where available','A methodology and freshness statement']},
 {id:3,title:'Where does liquidity go when markets close?',description:'Explore the mechanics of price discovery, spread formation and liquidity outside traditional market hours.',category:'Market structure',tag:'DEEP DIVE',reward:'0.12',submissions:0,color:'mint',icon:'o',difficulty:'Technical',deadline:'Preview',sponsor:'Example sponsor',status:'Open',brief:'Study how extended trading hours affect liquidity and reference prices. Use reproducible public data where available. Explain assumptions and distinguish observations from hypotheses.',deliverables:['Reproducible data and methodology','A concise analysis of spread and depth','Risks, limitations and unanswered questions']},
 {id:4,title:'Make smart contract risk understandable',description:'Turn common contract permissions and failure modes into a practical checklist for everyday researchers.',category:'Risk research',tag:'PUBLIC GOOD',reward:'0.06',submissions:0,color:'blue',icon:'o',difficulty:'Technical',deadline:'Preview',sponsor:'Example sponsor',status:'Open',brief:'Produce an accessible, evidence-led checklist for reviewing contract permissions, upgradeability and custody. This is educational research, not an audit or assurance report.',deliverables:['An approachable contract risk checklist','Annotated examples from public documentation','Clear boundaries between research and security audit']}
]);
const filtered = computed(() => missionItems.value.filter(m => (activeCategory.value==='All topics'||m.category===activeCategory.value) && (activeView.value!=='Saved'||previewSaved.value.includes(m.id)) && (activeView.value!=='My activity'||(account.value && m.creator?.toLowerCase()===account.value.toLowerCase())) && `${m.title} ${m.description}`.toLowerCase().includes(search.value.toLowerCase())));
const savedCount = computed(()=>previewSaved.value.length);
function notify(message){notice.value=message;setTimeout(()=>notice.value='',6000)}
function saveMission(m){previewSaved.value=previewSaved.value.includes(m.id)?previewSaved.value.filter(id=>id!==m.id):[...previewSaved.value,m.id];localStorage.setItem('proofora-saved',JSON.stringify(previewSaved.value))}
function scrollTo(id){document.getElementById(id)?.scrollIntoView({behavior:'smooth'});mobileNav.value=false}
async function updateWalletStats(){ if(!window.ethereum||!account.value) return; try { const p=new BrowserProvider(window.ethereum); walletBalance.value=formatEther(await p.getBalance(account.value)); if(configured.value){ const c=new Contract(CONTRACT_ADDRESS,CONTRACT_ABI,p); claimableAmount.value=formatEther(await c.claimable(account.value)); networkTotals.value={escrowed:formatEther(await c.totalEscrowed()),awarded:formatEther(await c.totalAwarded()),claimed:formatEther(await c.totalClaimed())}; } } catch(e){} }
async function connectWallet(){walletError.value='';if(!window.ethereum){walletError.value='No Ethereum wallet found. Install a compatible browser wallet, then return here.';return}connecting.value=true;try{const a=await window.ethereum.request({method:'eth_requestAccounts'});account.value=a[0]||'';chainId.value=await window.ethereum.request({method:'eth_chainId'}); await updateWalletStats();}catch(e){walletError.value=e.code===4001?'Connection was declined. You can try again when ready.':e.message}finally{connecting.value=false}}
async function switchNetwork(){if(!window.ethereum||!CHAIN_ID){notify('Network configuration is not available yet.');return}try{await window.ethereum.request({method:'wallet_switchEthereumChain',params:[{chainId:'0x'+BigInt(CHAIN_ID).toString(16)}]})}catch(e){if(e.code===4902&&RPC_URL){try{await window.ethereum.request({method:'wallet_addEthereumChain',params:[{chainId:'0x'+BigInt(CHAIN_ID).toString(16),chainName:'Robinhood Chain Testnet',nativeCurrency:{name:'Ether',symbol:'ETH',decimals:18},rpcUrls:[RPC_URL],blockExplorerUrls:EXPLORER_URL?[EXPLORER_URL]:[]}]})}catch(err){notify(err.message)}}else notify(e.message)}}
function accountsChanged(a){account.value=a[0]||''; updateWalletStats()}function chainChanged(c){chainId.value=c; updateWalletStats()}
function openCreate(){createOpen.value=true}
async function refreshMissions(){
 if(!configured.value || !RPC_URL) return;
 try { const { JsonRpcProvider } = await import('ethers'); const p=new JsonRpcProvider(RPC_URL); const c=new Contract(CONTRACT_ADDRESS, CONTRACT_ABI, p); const count=Number(await c.missionCount()); const rows=await c.getMissions(0, Math.min(count,100)); missionItems.value=rows.map((m,i)=>({id:i,title:m.title,descriptionURI:m.descriptionURI,description:'Open research mission. Read the brief URI for full scope and acceptance criteria.',category:m.category,tag:'ON-CHAIN BRIEF',reward:formatEther(m.totalEscrowed),submissions:Number(m.contributionCount),color:['peach','lavender','mint','blue'][i%4],icon:['S','O','=','+'][i%4],deadline:new Date(Number(m.deadline)*1000).toLocaleDateString(),sponsor:m.creator,status:m.closed?'Closed':'Open',brief:'Open the public brief URI to review scope and acceptance criteria.',deliverables:['Read the public brief and cite original sources','Submit a permanent evidence URI','Follow sponsor review and payout rules'],creator:m.creator})); } catch(e){ console.error(e); notify('Could not load missions from the configured RPC.'); }
}
async function loadContributions(){ if(!selected.value||!configured.value) return; try { const { JsonRpcProvider }=await import('ethers'); const p=new JsonRpcProvider(RPC_URL); const c=new Contract(CONTRACT_ADDRESS,CONTRACT_ABI,p); contributions.value=await c.getContributions(selected.value.id,0,100); } catch(e){ contributions.value=[] } }
watch(selected,()=>{ contributions.value=[]; loadContributions(); });
async function transact(kind, index, amount){
 if(!configured.value){notify('This is a preview. Configure a deployed contract to send transactions.');return}
 if(!account.value){await connectWallet();if(!account.value)return}
 if(!correctChain.value){await switchNetwork();return}
 busy.value=true; txHash.value='';
 try {
   const provider=new BrowserProvider(window.ethereum); const signer=await provider.getSigner(); const c=new Contract(CONTRACT_ADDRESS,CONTRACT_ABI,signer); let tx;
   if(kind==='fund'){ const amount=Number(contribution.value); if(!amount||amount<=0) throw new Error('Enter a contribution amount.'); tx=await c.fundMission(selected.value.id,{value:parseEther(String(amount))}); }
   else if(kind==='submit'){ if(!evidence.value.trim()) throw new Error('Enter a public evidence URI.'); tx=await c.contribute(selected.value.id,evidence.value.trim()); }
   else if(kind==='create'){ const f=missionForm.value; const deadline=Math.floor(new Date(f.deadline).getTime()/1000); if(!f.title||!f.uri||!f.description||!deadline||deadline<=Math.floor(Date.now()/1000)) throw new Error('Complete the mission fields with a future deadline.'); tx=await c.createMission(f.title,f.uri,f.category,deadline,{value:parseEther(String(f.reward||0))}); }
   else if(kind==='claim'){ tx=await c.claimRewards(); }
   else if(kind==='refund'){ tx=await c.refundUnallocated(selected.value.id); }
   else if(kind==='approve'){ const amt=Number(amount||contribution.value); if(!amt||amt<=0) throw new Error('Enter an approval amount.'); tx=await c.approveContribution(selected.value.id,Number(index),parseEther(String(amt))); }
   txHash.value=tx.hash; notify('Transaction submitted. Waiting for confirmation?'); await tx.wait(); notify('Transaction confirmed on Robinhood Chain testnet.'); await refreshMissions(); await updateWalletStats();
 } catch(e){ const msg=e?.shortMessage||e?.reason||e?.message||'Transaction failed.'; notify(msg.length>160?msg.slice(0,157)+'?':msg); } finally {busy.value=false}
}
function closeModal(){selected.value=null;createOpen.value=false;guideOpen.value=false;txHash.value=''}
function onKey(e){if(e.key==='Escape')closeModal()}
onMounted(async()=>{document.addEventListener('keydown',onKey); refreshMissions();if(window.ethereum){window.ethereum.on?.('accountsChanged',accountsChanged);window.ethereum.on?.('chainChanged',chainChanged);try{const a=await window.ethereum.request({method:'eth_accounts'});account.value=a[0]||'';chainId.value=await window.ethereum.request({method:'eth_chainId'}); await updateWalletStats()}catch{}}});
onUnmounted(()=>{document.removeEventListener('keydown',onKey);window.ethereum?.removeListener?.('accountsChanged',accountsChanged);window.ethereum?.removeListener?.('chainChanged',chainChanged)});
</script>

<template>
<div class="app-shell">
  <div class="announcement"><span class="tiny-dot"></span> A new chapter for open financial research. <button @click="scrollTo('missions')">Explore Robinhood Chain testnet <span>-></span></button></div>
  <header class="site-header"><a class="logo" href="#" aria-label="Proofora home"><img class="brand-logo-image" :src="brandLogoUrl" width="40" height="40" alt="" aria-hidden="true"/>Proofora<span class="logo-period">.</span></a><nav :class="{open:mobileNav}"><button @click="scrollTo('missions')">Mission board</button><button @click="scrollTo('how-it-works')">How it works</button><button @click="guideOpen=true">Field notes <span>-></span></button></nav><div class="header-actions"><span v-if="account" class="balance-chip">{{Number(walletBalance).toFixed(3)}} ETH</span><button class="wallet-button" @click="connectWallet" :disabled="connecting"><svg width="15" height="15" viewBox="0 0 20 20" fill="none"><rect x="2" y="4" width="16" height="13" rx="3" stroke="currentColor" stroke-width="1.5"/><path d="M13 8H18V13H13V8Z" stroke="currentColor"/><path d="M3 4L14 1V4" stroke="currentColor"/></svg>{{connecting?'Connecting?':shortAccount}}</button><button class="mobile-toggle" @click="mobileNav=!mobileNav" aria-label="Toggle navigation">MENU</button></div></header>
  <div v-if="walletError" class="wallet-error">{{walletError}} <button @click="walletError=''" aria-label="Dismiss error">?</button></div>
  <main>
    <section class="hero">
      <div class="hero-copy"><div class="eyebrow"><span class="sun-icon">*</span> CURIOSITY IS CAPITAL</div><h1>Follow curiosity.<br>Fund <em>conviction.</em></h1><p class="hero-intro">The next generation of finance deserves better research. Fund the questions that matter. Make the evidence public. Reward the people who connect the dots.</p><div class="hero-cta"><button class="button dark" @click="scrollTo('missions')">Find your first mission <span>-></span></button><button class="text-link" @click="scrollTo('how-it-works')"><span class="play-circle">*</span> See how it works</button></div><div class="hero-proof"><div class="chain-symbol">-></div><div>Built for <strong>Robinhood Chain</strong><small>Independent by design. Open by default.</small></div><span class="testnet-label">TESTNET</span></div></div>
      <div class="hero-visual" aria-label="Illustration of research turning into shared knowledge"><div class="visual-grid"></div><div class="orbital-line orbit-one"></div><div class="orbital-line orbit-two"></div><span class="visual-star star-one">*</span><span class="visual-star star-two">+</span><div class="floating-tag tag-evidence"><span>-></span> Evidence, not noise.</div><div class="research-card"><div class="research-top"><span class="mini-logo">S-></span><span>RESEARCH NOTE / 001</span><span class="three-dots">*</span></div><div class="paper-title">A clearer view.<br><i>A shared advantage.</i></div><div class="chart-grid"><span>CONVICTION</span><svg viewBox="0 0 360 125" preserveAspectRatio="none"><defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop stop-color="#ed6848" stop-opacity=".28"/><stop offset="1" stop-color="#ed6848" stop-opacity="0"/></linearGradient></defs><path d="M0 108L38 91L70 98L107 62L140 79L177 40L217 53L259 25L301 32L360 0V125H0Z" fill="url(#area)"/><path d="M0 108L38 91L70 98L107 62L140 79L177 40L217 53L259 25L301 32L360 0" fill="none" stroke="#e75f3e" stroke-width="3" stroke-linecap="round"/></svg><div class="chart-axis"><span>BETTER QUESTIONS</span><span>BETTER SIGNAL</span></div></div><div class="paper-bottom"><div class="avatar-stack"><span>JR</span><span>AL</span><span>MK</span></div><span>One question. Many perspectives.</span><span>-></span></div></div><div class="floating-tag tag-funded"><span class="circle-check">*</span><div>Curiosity, coordinated.<small>From question to public good</small></div></div><div class="visual-caption">THE RESEARCH COMMONS <span>-></span> EST. 2026</div></div>
    </section>
    <section class="principles-strip"><span>A SMALL SHIFT.<br><strong>A BIGGER PICTURE.</strong></span><div><span class="line-icon">*</span><p>Questions worth asking</p></div><div><span class="line-icon">*</span><p>Evidence anyone can verify</p></div><div><span class="line-icon">-></span><p>Rewards that follow the work</p></div></section>
    <section id="missions" class="mission-section"><div class="section-heading"><div><div class="eyebrow">THE MISSION BOARD <span class="small-line"></span></div><h2>Find your next <em>rabbit hole.</em></h2><p>Big questions. Specific briefs. A place for your kind of curious.</p></div><button class="button outline" @click="openCreate">Create a mission <span>+</span></button></div>
      <div class="mode-notice" v-if="!configured"><span class="mode-dot"></span><strong>Explore the preview</strong><span>These are sample briefs and illustrative rewards. Live missions appear after contract deployment.</span><button @click="guideOpen=true">How to go live -></button></div>
      <div class="board-toolbar"><div class="board-tabs"><button v-for="view in ['All missions','Saved','My activity']" :class="{active:activeView===view}" @click="activeView=view">{{view}} <span v-if="view==='Saved'">{{savedCount}}</span><span v-if="view==='All missions'">{{missionItems.length}}</span></button></div><label class="search-input"><svg width="16" height="16" viewBox="0 0 20 20" fill="none"><circle cx="8" cy="8" r="5.5" stroke="currentColor" stroke-width="1.5"/><path d="M12 12L17 17" stroke="currentColor" stroke-width="1.5"/></svg><input v-model="search" placeholder="Search your curiosity?" aria-label="Search missions"></label></div>
      <div class="topic-filters"><button v-for="topic in topics" :class="{active:activeCategory===topic}" @click="activeCategory=topic">{{topic}}</button><span class="result-count">{{filtered.length}} {{filtered.length===1?'mission':'missions'}}</span></div>
      <div class="mission-grid" v-if="filtered.length"><article v-for="m in filtered" :key="m.id" class="mission-card" @click="selected=m" tabindex="0" @keydown.enter="selected=m"><div class="mission-art" :class="m.color"><div class="mission-art-lines"></div><span class="mission-tag">{{m.tag}}</span><span class="mission-art-symbol">{{m.icon}}</span><button class="bookmark" :class="{saved:previewSaved.includes(m.id)}" @click.stop="saveMission(m)" :aria-label="previewSaved.includes(m.id)?'Unsave mission':'Save mission'"><svg width="17" height="19" viewBox="0 0 17 19" :fill="previewSaved.includes(m.id)?'currentColor':'none'"><path d="M3 2H14V17L8.5 13.5L3 17V2Z" stroke="currentColor" stroke-width="1.3"/></svg></button><span class="art-footer">PROOFORA RESEARCH COMMONS <span>0{{m.id}} -></span></span></div><div class="mission-body"><div class="mission-meta"><span>{{m.category}}</span><span class="open-status"><i></i>{{m.status}}</span></div><h3>{{m.title}}</h3><p>{{m.description}}</p><div class="mission-bottom"><div><span class="reward-label">{{configured?'REWARD POOL':'EXAMPLE REWARD'}}</span><strong>{{m.reward}} <small>ETH</small></strong></div><button class="card-arrow" aria-label="Open mission">-></button></div></div></article></div>
      <div v-else class="empty-state"><span>*</span><h3>{{activeView==='Saved'?'Keep a little curiosity for later.':activeView==='My activity'?'Your research story starts here.':'No missions found.'}}</h3><p>{{activeView==='Saved'?'Tap the bookmark on a mission to save it on this device.':activeView==='My activity'?'Connect your wallet to see missions you create.':'Try another topic or a different search term.'}}</p><button class="text-link" @click="activeView='All missions';activeCategory='All topics';search=''">Explore all missions -></button></div>
      <div class="board-footer"><span><i class="tiny-dot"></i> Public briefs. Transparent rewards. Verifiable contributions.</span><button @click="guideOpen=true">Read the contributor guide -></button></div>
    </section>
    <section id="how-it-works" class="how-section"><div class="section-heading"><div><div class="eyebrow">LESS NOISE. MORE KNOWING.</div><h2>Good research is<br>a <em>team sport.</em></h2></div><p>From a good question to a useful public resource.<br>One transparent workflow, on Robinhood Chain.</p></div><div class="steps"><article><div class="step-top"><span class="step-number">01</span><svg viewBox="0 0 80 60" fill="none"><rect x="15" y="10" width="45" height="35" rx="2" stroke="currentColor"/><path d="M25 20H50M25 27H43M25 34H37M48 40L64 24M56 24H64V32" stroke="currentColor" stroke-width="1.4"/></svg></div><h3>Put a question to work.</h3><p>Create a focused brief, set a deadline and fund its reward pool. Other sponsors can add to the same mission.</p><span>FOR THE QUESTION ASKERS -></span></article><article><div class="step-top"><span class="step-number">02</span><svg viewBox="0 0 80 60" fill="none"><circle cx="35" cy="27" r="17" stroke="currentColor"/><path d="M47 39L62 53M24 27H46M35 16V38" stroke="currentColor" stroke-width="1.4"/></svg></div><h3>Bring the receipts.</h3><p>Investigate, compare and connect the dots. Submit a public research URI so the evidence stays independently accessible.</p><span>FOR THE DEEP DIVERS -></span></article><article><div class="step-top"><span class="step-number">03</span><svg viewBox="0 0 80 60" fill="none"><path d="M18 43L31 30L42 37L63 14M49 14H63V28" stroke="currentColor" stroke-width="1.4"/><path d="M18 49H65" stroke="currentColor"/></svg></div><h3>Make insight a public good.</h3><p>The sponsor reviews the contribution. Accepted work earns an on-chain reward and adds to a growing research commons.</p><span>FOR EVERYONE WHO LEARNS -></span></article></div></section>
    <section class="manifesto"><div class="manifesto-shape"><span>S</span><svg viewBox="0 0 250 250"><circle cx="125" cy="125" r="115"/><ellipse cx="125" cy="125" rx="115" ry="50" transform="rotate(-35 125 125)"/><path d="M25 192L227 53M207 53H227V73"/></svg><span class="manifesto-star">*</span></div><div><div class="eyebrow">A DIFFERENT KIND OF EDGE</div><h2>Markets move fast.<br><em>Understanding lasts.</em></h2><p>We believe the most valuable thing a community can build is a better shared understanding. Proofora gives curiosity a structure, useful work a reward, and everyone a seat at the research table.</p><button class="button dark" @click="openCreate">Ask a better question <span>-></span></button><span class="manifesto-note">No platform token. No promised returns. Just useful work.</span></div></section>
    <section class="faq-section"><div><div class="eyebrow">A FEW GOOD QUESTIONS</div><h2>Before you <em>jump in.</em></h2></div><div class="faqs"><details open><summary>Is Proofora affiliated with Robinhood?<span>+</span></summary><p>No. Proofora is an independent project built for Robinhood Chain. It is not affiliated with, endorsed by or operated by Robinhood Markets, Inc.</p></details><details><summary>Are rewards an investment return?<span>+</span></summary><p>No. Rewards are payments for research accepted by a mission sponsor. There is no platform token, yield promise or guaranteed reward. Testnet ETH has no intended monetary value.</p></details><details><summary>Who decides whether research is accepted?<span>+</span></summary><p>The mission creator reviews submissions against the published brief. Sponsor judgment is a trust assumption. Contributors should read the scope and payout terms before doing work.</p></details><details><summary>What happens to unused mission funds?<span>+</span></summary><p>Unallocated funds follow the contract?s deadline and refund rules. Review the mission details and contract documentation before contributing. On-chain payments are public.</p></details></div></section>
  </main>
  <footer><div class="footer-main"><a class="logo" href="#"><img class="brand-logo-image" :src="brandLogoUrl" width="40" height="40" alt="" aria-hidden="true"/>Proofora<span class="logo-period">.</span></a><p>A little more curious.<br>A lot more informed.<br><a class="social-link" href="https://x.com/ProoforaFun" target="_blank" rel="noopener noreferrer" aria-label="Proofora on X">X / Twitter</a></p><button @click="scrollTo('missions')">Mission board -></button><button @click="guideOpen=true">Contributor guide -></button></div><div class="footer-bottom"><span>? 2026 Proofora. An independent research commons.</span><span class="footer-network"><i class="tiny-dot"></i> Robinhood Chain ? Testnet</span><button @click="window.scrollTo({top:0,behavior:'smooth'})">Back to top ?</button></div><p class="legal">Independent project. Not affiliated with Robinhood Markets, Inc. Research is educational and does not constitute investment advice. Preview content is illustrative.</p></footer>
  <div class="modal-overlay" v-if="selected||createOpen||guideOpen" @click.self="closeModal"><section class="modal" role="dialog" aria-modal="true" :aria-label="selected?'Mission details':createOpen?'Create a mission':'Contributor guide'"><button class="modal-close" @click="closeModal" aria-label="Close dialog">?</button>
    <template v-if="selected"><div class="eyebrow">{{configured?'MISSION #'+selected.id:'SAMPLE MISSION ? PREVIEW'}}</div><h2>{{selected.title}}</h2><div class="detail-meta"><span>{{selected.category}}</span><strong>{{selected.reward}} ETH <small>{{configured?'reward pool':'illustrative reward'}}</small></strong></div><p>{{selected.brief||selected.description}}</p><h4>What useful looks like</h4><ul><li v-for="line in selected.deliverables" :key="line">{{line}}</li></ul><div class="detail-warning" v-if="!configured">This brief is an example. No live escrow exists and no transactions can be submitted.</div><div class="form-block"><h4>Add to the reward pool</h4><label>Contribution (testnet ETH)<input v-model="contribution" type="number" min="0" step="0.001" placeholder="0.01"></label><button class="button dark" :disabled="!configured||busy" @click="transact('fund')">Fund this mission -></button></div><div class="form-block"><h4>Submit your research</h4><label>Public evidence URI<input v-model="evidence" placeholder="ipfs://... or https://..."></label><p class="field-help">Publish your research at a permanent, accessible URI. Never include private information in an on-chain submission.</p><button class="button dark" :disabled="!configured||busy" @click="transact('submit')">Submit contribution -></button></div><div v-if="configured && contributions.length" class="contribution-list"><h4>Submitted evidence</h4><div v-for="(c,i) in contributions" :key="i" class="contribution-row"><a :href="c.evidenceURI" target="_blank" rel="noopener">{{c.evidenceURI}}</a><span>{{c.approvedByCreator?'Approved':'Pending review'}}</span><button v-if="account && selected.creator && account.toLowerCase()===selected.creator.toLowerCase() && !c.approvedByCreator" class="text-link" @click="transact('approve',i,contribution)">Approve {{contribution||'amount'}} ETH</button></div></div><div class="mission-actions"><button v-if="configured" class="button outline" :disabled="busy" @click="transact('claim')">Claim available rewards</button><button v-if="configured && account && selected.creator && account.toLowerCase()===selected.creator.toLowerCase()" class="button outline" :disabled="busy" @click="transact('refund')">Refund after deadline</button></div><button class="text-link" @click="saveMission(selected)">{{previewSaved.includes(selected.id)?'Saved on this device':'Bookmark this mission ->'}}</button></template>
    <template v-else-if="createOpen"><div class="eyebrow">START WITH A GOOD QUESTION</div><h2>Create a mission.</h2><p>Give contributors a precise brief, a clear deadline and a funded reward.</p><div class="detail-warning" v-if="!configured">You can draft your brief here. Publishing becomes available after a deployed contract is configured.</div><form @submit.prevent="transact('create')"><label>Mission title<input v-model="missionForm.title" maxlength="120" placeholder="What would you like to understand?" required></label><label>Topic<select v-model="missionForm.category"><option v-for="topic in topics.slice(1)">{{topic}}</option></select></label><label>Research brief<textarea v-model="missionForm.description" rows="4" placeholder="Define the question, scope and acceptance criteria." required></textarea></label><label>Public brief URI<input v-model="missionForm.uri" placeholder="ipfs://... or https://..." required></label><div class="form-row"><label>Reward (testnet ETH)<input v-model="missionForm.reward" type="number" min="0.000001" step="0.000001" placeholder="0.05" required></label><label>Submission deadline<input v-model="missionForm.deadline" type="datetime-local" required></label></div><button class="button dark" type="submit" :disabled="!configured||busy">{{busy?'Waiting for wallet?':'Publish & fund mission'}} -></button></form></template>
    <template v-else><div class="eyebrow">THE PROOFORA FIELD GUIDE</div><h2>Good questions.<br><em>Clear expectations.</em></h2><h4>For sponsors</h4><p>State a narrow research question. Publish objective acceptance criteria, primary sources and a reasonable deadline. Reward useful evidence, including findings that challenge your original assumptions.</p><h4>For contributors</h4><p>Read the brief before starting. Separate facts, assumptions and interpretation. Cite original sources and publish research at an accessible URI. Sponsors decide which work they accept; a submission does not guarantee a reward.</p><h4>Go from preview to live</h4><p>Deploy the included escrow contract to Robinhood Chain testnet, then set the contract address in <code>src/config.js</code> or your environment configuration. The mission board reads contract events and balances once connected.</p><h4>Know the boundaries</h4><p>This is an independent testnet application. It has not been audited. Research is educational; it is not personalized investment advice. Keep private information off-chain.</p></template>
    <a v-if="txHash&&EXPLORER_URL" :href="EXPLORER_URL+'/tx/'+txHash" target="_blank" rel="noopener noreferrer" class="text-link">View transaction -></a>
  </section></div><div class="toast" v-if="notice" role="status"><span>-></span>{{notice}}<button @click="notice=''" aria-label="Dismiss notification">?</button></div>
</div>
</template>

